# permissions for end users to view bridgeports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bridgeport-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mikrotik-operator
    app.kubernetes.io/part-of: mikrotik-operator
    app.kubernetes.io/managed-by: kustomize
  name: bridgeport-viewer-role
rules:
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - bridgeports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - bridgeports/status
  verbs:
  - get
