# permissions for end users to edit bridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bridge-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mikrotik-operator
    app.kubernetes.io/part-of: mikrotik-operator
    app.kubernetes.io/managed-by: kustomize
  name: bridge-editor-role
rules:
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - bridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - bridges/status
  verbs:
  - get
