---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - routers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - routers/finalizers
  verbs:
  - update
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - routers/status
  verbs:
  - get
  - patch
  - update
