apiVersion: routeros.mikrotik.com/v1alpha1
kind: Address
metadata:
  labels:
    app.kubernetes.io/name: address
    app.kubernetes.io/instance: address-sample
    app.kubernetes.io/part-of: mikrotik-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mikrotik-operator
  name: address-sample
spec:
  # TODO(user): Add fields here
